### ISSUE TITLE
Unable to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by kiklop74** [mbfoss/gnethogs#5]
First of all apat from the libraries mentioned in the readme Ubuntu 14.04 requires this as well:

`sudo apt-get install libtool autopoint`

After that is installed and autoogen.sh is running we get this:

`./autogen.sh` 
`Regenerating autotools files`
`autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac`
`               file requires the infrastructure from gettext-0.19.3 but this version`
`               is older. Please upgrade to gettext-0.19.3 or newer.`
`autopoint: *** Stop.`
`autoreconf: autopoint failed with exit status: 1`

Ubuntu 14.04 ships with gettext 0.18.3

**Comment by kiklop74** [comment]
So I modified configure.ac and downgraded gettext version. Program compiled ok.
When I run it it crashes right away. Attaching the strace log
[out.log.zip](https://github.com/mbfoss/gnethogs/files/690139/out.log.zip)

**Comment by mbfoss** [comment]
I just pushed a fix to this.
It was previously incompatible with GTK < 3.14
now it will work with GTK 3.10 (shipped with ubuntu 14.04) 
it may not integrate very will with the window manager though.
Cheers!
