### ISSUE TITLE
Unable to compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by abdalmoniem** [mbfoss/gnethogs#6]
the compilation fails with too many errors, here are some screenshots:

![screenshot from 2017-11-12 06 37 27](https://user-images.githubusercontent.com/11904264/32696000-3c04dd62-c774-11e7-8d68-9af947b03fbe.png)
![screenshot from 2017-11-12 06 37 39](https://user-images.githubusercontent.com/11904264/32696001-3c2759b4-c774-11e7-91f9-35a31321a7a7.png)
![screenshot from 2017-11-12 06 37 46](https://user-images.githubusercontent.com/11904264/32696002-3c4985ac-c774-11e7-8935-699530490fbe.png)

**Comment by mbfoss** [comment]
Hi
This looks like issue with gcc version
Please update your gcc packages and try again
If this does not fix it, there is probably some configuration issue in the build files...
Will look at this in more details when I get some free time.
Cheers

**Comment by mbfoss** [comment]
Current autoconf settings does not explicitly require c++11, which is problematic with old versions of gcc
this need to be fixed by adding a module like this: https://gitlab.inria.fr/MarTo/marto/-/blob/1490c89f5d6f77da066ab9eacde7170b4aca5d7c/m4/ax_cxx_compile_stdcxx_11.m4

**Comment by abdalmoniem** [comment]
thank you very much, will try and update you.
